## Python - Numpy Guide


#### Priyaranjan Mohanty

### Numpy : what is it ?

Numpy is the most basic and a powerful package for working with data in python.

If you are going to work on data analysis or machine learning projects, then having a solid understanding of numpy is nearly mandatory.

Because other packages for data analysis (like pandas) is built on top of numpy and the scikit-learn package which is used to build machine learning applications works heavily with numpy as well.

So what does numpy provide?

At the core, numpy provides the excellent ndarray objects, short for n-dimensional arrays.

In a ‘ndarray’ object, aka ‘array’, you can store multiple items of the same data type. It is the facilities around the array object that makes numpy so convenient for performing math and data manipulations.

You might wonder, ‘I can store numbers and other objects in a python list itself and do all sorts of computations and manipulations through list comprehensions, for-loops etc. What do I need a numpy array for?’

Well, there are very significant advantages of using numpy arrays overs lists.

To understand this, let’s first see how to create a numpy array.

### How to create NDArray ( Numpy Array )

There are multiple ways to create a numpy array. 

However one of the most common ways is to create one from a list or a list like an object by passing it to the np.array function.

In [1]:
# Install Numpy 

!pip install numpy

In [2]:
# Import Numpy 

import numpy as np

In [3]:
# Create an 1 dimensional array from a list

list1 = [0,1,2,3,4]

Arr_1d = np.array(list1)

In [4]:
# Print the array and its type
print(type(Arr_1d))

print("\n")

print(Arr_1d)

<class 'numpy.ndarray'>


[0 1 2 3 4]


In [5]:
# Print the shape of the Array

print(Arr_1d.shape)

(5,)


The key difference between an array and a list is, arrays are designed to handle vectorized operations while a python list is not.

That means, if you apply a function it is performed on every item in the array, rather than on the whole array object.

Let’s suppose you want to add the number 2 to every item in the list. The intuitive way to do it is something like this:

In [8]:
print(list1)

[0, 1, 2, 3, 4]


In [9]:
list1 + 2

TypeError: can only concatenate list (not "int") to list

In [10]:
print(Arr_1d)

[0 1 2 3 4]


In [11]:
Arr_1d + 2

array([2, 3, 4, 5, 6])

### Next Step - Lets create 2 Dimensional Array 



In [12]:
# Create a 2d array from a list of lists

list_2D = [[0,1,2,3], 
           [4,5,6,7], 
           [8,9,10,11]]

Arr_2D = np.array(list_2D)

In [13]:
Arr_2D

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [14]:
print(type(Arr_2D))

print("\n")

print(Arr_2D)

print("\n")

print(Arr_2D.shape)

<class 'numpy.ndarray'>


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


(3, 4)


In [17]:
# We can also create a 2-D Array from a flat list ( Not a nested list )

List_Num = [0,1,2,3,4,5,6,7,8,9,10,11]

# Array_1D_2 = np.array(List_Num)

# Array_2D_2 = Array_1D_2.reshape(3,4)

Array_2D_2 = np.array(List_Num).reshape(3,4)

Array_2D_2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [18]:
Array_2D_2.shape

(3, 4)

In [19]:
Array_2D_3 = Array_2D_2.reshape(6,2)

Array_2D_3

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

We can also specify the datatype by setting the dtype argument. 

Some of the most commonly used numpy dtypes are: 'float', 'int', 'bool', 'str'

In [20]:
# Create a float 2d array

Arr_2D_2 = np.array(list_2D, dtype='float')

print(Arr_2D_2)

print(Arr_2D_2.dtype)

[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]]
float64


#### Note -

A numpy array must have all items to be of the same data type, unlike lists. This is another significant difference.

### Note :

We can always convert a Numpy Array back to List 

In [21]:
print(Arr_1d)

print(type(Arr_1d))

[0 1 2 3 4]
<class 'numpy.ndarray'>


In [22]:
# Convert an ndarray to list 

print(Arr_1d.tolist())

print("\n")

print(type(Arr_1d.tolist()))

[0, 1, 2, 3, 4]


<class 'list'>


In [23]:
print(Arr_2D)

print("\n")

print(type(Arr_2D))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


<class 'numpy.ndarray'>


In [25]:
# Convert 2-d array to list 

print(Arr_2D.tolist())

print("\n")

print(type(Arr_2D.tolist()))

[[0, 1, 2, 3], [4, 5, 6, 7], [8, 9, 10, 11]]


<class 'list'>
